export const carcolor : { [key:string]: string} = {
    'Mercedes Benz' : 'mercedes.png',
    'Chevrolet' : 'chevrolet.png',
    'Ford': 'ford.png',
    'BMW': 'bmw.png',
    'Porsche': 'porsche.png',
    'McLaren': 'mclaren.png',
    'Audi': 'audi.png',
    'Ferrari': 'ferrari.png',
    'Toyota': 'toyota.png',
    'Renault': 'renault.png',
    'Aston Martin': 'astonmartin.png',
    'Alfa Romeo': 'alfaromeo.png',
    'Nissan': 'nissan.png',
    'Lamborghini': 'lamborghini.png',
    'Lotus': 'lotus.png',
    'Peugeot': 'peugeot.png',
    'Red Bull Racing': 'redbullracing.png',
    'Volkswagen': 'volkswagen.png',
    'Bugatti': 'bugatti.png',
    'Koenigsegg': 'koenigsegg.png'
}